version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kinesis-consumer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1w3284xu0m53i"
s3_prefix = "kinesis-consumer"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "KinesisStreamName=\"dna-kinesis\" ESDomainName=\"dna-es\" ElasticsearchVersion=\"7.1\""

